### ISSUE TITLE
Same here unfortunately :(

### ISSUE THREAD

**Issue by sloppyjuicy** [sqren/alfred-currency#5]
Same here unfortunately :(

<img width="60⁰3" alt="Screenshot 2021-04-09 at 19 18 40" src="https://user-images.githubusercontent.com/5272004/114230271-798f1200-9968-11eb-8bd8-3e6d0a31e9a2.png">

I got a similar behaviour a while back but after syncing Alfred's preferences between computers somehow it got fixed. Now doesn't work on any of the machines...

A solution would be highly appreciated.
Thank you

_Originally posted by @olgv in https://github.com/sqren/alfred-currency/issues/4#issuecomment-816912934_

**Comment by olgv** [comment]
I don't think the dev. cares about this at all. 

Hey @sqren how much would cost us to get this fixed?

**Comment by sorenlouv** [comment]
Hey there,

I'm not using this workflow myself anymore so haven't been maintaining it for a while. Happily surprised to see it still being used.

I can't promise I have time in the near future to look into this so if someone can create a PR that fixes this I'll gladly merge.

**Comment by sorenlouv** [comment]
Looking into this a bit it looks like the underlying service for calculating exchange rates (exchangeratesapi.io) has started requiring an access token. The free service only comes with 250 lookups per month, so I cannot create a shared access token and bundle that with the app, since that would be consumed in no time.

Only other option is to switch to another service that has higher limits on anonymous lookups or require every user to signup on exchangeratesapi.io
